name: Build AWS-CLI with JDK 11

on:
  push:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - 'jdk11/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_HUB_USERNAME: ${{ secrets. DOCKER_HUB_USERNAME }} 
        DOCKER_HUB_PASSWORD: ${{ secrets. DOCKER_HUB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
        echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin

    - name: Build & Push Docker Image
      run: |
        cd jdk11
        IMAGE_NAME=ringcentral/aws-cli
        GH_DOCKER_PKG_IMAGE_NAME=docker.pkg.github.com/ringcentral-docker/aws-cli/aws-cli

        VERSION="jdk$(awk -F '[:]' '/FROM/ {print $2}' Dockerfile)"

        docker build --tag ${IMAGE_NAME} --file Dockerfile .
        
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}"

        docker push "${IMAGE_NAME}:${VERSION}"

        docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:${VERSION}"

        docker push "${GH_DOCKER_PKG_IMAGE_NAME}:${VERSION}"